import type { InstitutionalTimelineModel, TimelineConfig } from "@/lib/customer/timeline/timeline.types";

export const institutionalTimelineConfig: TimelineConfig = {
  title: "Institutional Activity Timeline",
  subtitle: "Cross-capability event visibility for the active customer",
  filterTitle: "Filters",
  summaryTitle: "Timeline Summary",
  summarySubtitle: "Configuration-driven timeline counters and posture",
  timelineTitle: "Events",
  timelineSubtitle: "Generic institutional events with no persistence coupling",
  filters: ["All", "Documents", "Relationship", "Approvals", "Funding", "AI"],
};

export const defaultInstitutionalTimelineModel: InstitutionalTimelineModel = {
  summary: [
    {
      id: "metric-events",
      label: "Total Events",
      value: "9",
    },
    {
      id: "metric-open-actions",
      label: "Open Actions",
      value: "3",
    },
    {
      id: "metric-critical",
      label: "Critical Alerts",
      value: "1",
    },
  ],
  events: [
    {
      id: "timeline-1",
      eventType: "Customer Created",
      occurredAt: "2026-07-16T09:00:00.000Z",
      title: "Customer profile initialized",
      description: "Customer workspace context and baseline profile were created.",
      actor: "Institution Onboarding",
      filter: "AI",
    },
    {
      id: "timeline-2",
      eventType: "Passport Updated",
      occurredAt: "2026-07-17T11:15:00.000Z",
      title: "Business Passport refreshed",
      description: "Identity and governance segments were updated for current review cycle.",
      actor: "Business Passport",
      filter: "AI",
    },
    {
      id: "timeline-3",
      eventType: "Document Uploaded",
      occurredAt: "2026-07-18T08:40:00.000Z",
      title: "Compliance document uploaded",
      description: "Required compliance artifact entered document intake.",
      actor: "Operations",
      filter: "Documents",
    },
    {
      id: "timeline-4",
      eventType: "Document Verified",
      occurredAt: "2026-07-18T16:25:00.000Z",
      title: "Document verification completed",
      description: "Uploaded document passed validation checks.",
      actor: "Evidence Validator",
      filter: "Documents",
    },
    {
      id: "timeline-5",
      eventType: "Relationship Updated",
      occurredAt: "2026-07-19T10:00:00.000Z",
      title: "Relationship plan updated",
      description: "Engagement plan was updated following client call.",
      actor: "Relationship Manager",
      filter: "Relationship",
    },
    {
      id: "timeline-6",
      eventType: "Approval Requested",
      occurredAt: "2026-07-20T09:10:00.000Z",
      title: "Approval package submitted",
      description: "Funding readiness approval package entered governance workflow.",
      actor: "Relationship Manager",
      filter: "Approvals",
    },
    {
      id: "timeline-7",
      eventType: "Approval Completed",
      occurredAt: "2026-07-22T15:45:00.000Z",
      title: "Approval review checkpoint completed",
      description: "Credit review completed with conditional remarks.",
      actor: "Credit Committee",
      filter: "Approvals",
    },
    {
      id: "timeline-8",
      eventType: "Funding Approved",
      occurredAt: "2026-07-23T09:30:00.000Z",
      title: "Funding allocation approved",
      description: "Approved amount is available for scheduled utilization.",
      actor: "Treasury",
      filter: "Funding",
    },
    {
      id: "timeline-9",
      eventType: "Funding Released",
      occurredAt: "2026-07-24T11:00:00.000Z",
      title: "Funding release initiated",
      description: "First funding release scheduled under active facility terms.",
      actor: "Treasury",
      filter: "Funding",
    },
  ],
};
