import type { Approval } from "./Approval";

export const sampleApprovals: Approval[] = [
  {
    id: "approval-001",
    stage: "Relationship Manager",
    approver: "Aisha Khan",
    role: "Relationship Manager",
    status: "approved",
    decisionDate: "2026-06-30T09:15:00Z",
    comments: "Customer profile reviewed and onboarding prerequisites satisfied.",
    slaHours: 4,
  },
  {
    id: "approval-002",
    stage: "Credit Analyst",
    approver: "Mina Haddad",
    role: "Credit Analyst",
    status: "approved",
    decisionDate: "2026-06-30T10:00:00Z",
    comments: "Credit metrics aligned with underwriting policy.",
    slaHours: 6,
  },
  {
    id: "approval-003",
    stage: "Risk Officer",
    approver: "Daniel Brooks",
    role: "Risk Officer",
    status: "pending",
    comments: "Awaiting final exposure review before recommendation.",
    slaHours: 8,
  },
  {
    id: "approval-004",
    stage: "Legal",
    approver: "Sofia Alvarez",
    role: "Legal",
    status: "waiting",
    comments: "Document package pending legal sign-off.",
    slaHours: 12,
  },
  {
    id: "approval-005",
    stage: "Treasury",
    approver: "Omar Rahman",
    role: "Treasury",
    status: "waiting",
    comments: "Funding allocation pending treasury confirmation.",
    slaHours: 10,
  },
  {
    id: "approval-006",
    stage: "Investment Committee",
    approver: "Priya Nair",
    role: "Investment Committee",
    status: "waiting",
    comments: "Escalated for committee review on structure and pricing.",
    slaHours: 24,
  },
  {
    id: "approval-007",
    stage: "CEO",
    approver: "Liam Chen",
    role: "CEO",
    status: "waiting",
    comments: "Final executive approval pending board-ready submission.",
    slaHours: 16,
  },
];
