/**
 * Executive verdict bands for orchestration-level decisions.
 */
export enum VerdictBand {
	Proceed = "Proceed",
	ProceedWithConditions = "Proceed with Conditions",
	Hold = "Hold",
	DoNotProceed = "Do Not Proceed",
}

/**
 * Data model for an executive verdict generated by ATLAS orchestration.
 */
export interface Verdict {
	band: VerdictBand;
	title: string;
	summary: string;
	issuedAt: string;
}
