export enum WorkflowAction {
  UPDATE_PRICING = "UPDATE_PRICING",
  START_CREDIT = "START_CREDIT",
  APPROVE_CREDIT = "APPROVE_CREDIT",
  START_RISK = "START_RISK",
  APPROVE_RISK = "APPROVE_RISK",
  UPLOAD_DOCUMENT = "UPLOAD_DOCUMENT",
  COMPLETE_DOCUMENTATION = "COMPLETE_DOCUMENTATION",
  START_FUNDING = "START_FUNDING",
  COMPLETE_FUNDING = "COMPLETE_FUNDING",
  RECEIVE_PAYMENT = "RECEIVE_PAYMENT",
}
