import type {
  RelationshipPanelConfig,
  RelationshipPanelModel,
} from "@/lib/customer/relationship/relationship-panel.types";

export const relationshipPanelConfig: RelationshipPanelConfig = {
  title: "Relationship Journey",
  subtitle: "Institution relationship composition layer inside the customer workspace",
  workspaceLabel: "Customer Relationship Surface",
  healthTitle: "Relationship Health",
  healthSubtitle: "Operational relationship posture provided by upstream capability projections",
  summaryTitle: "Summary",
  summarySubtitle: "Canonical relationship context and ownership",
  timelineTitle: "Timeline",
  timelineSubtitle: "Generic interaction events for the active relationship",
  insightsTitle: "Institutional Insights",
  insightsSubtitle: "Framework recommendations for future AI and intelligence composition",
  nextActionsTitle: "Recommended Next Actions",
  nextActionsSubtitle: "Configuration-driven relationship action queue",
};

export const defaultRelationshipPanelModel: RelationshipPanelModel = {
  health: {
    score: "82",
    status: "Stable",
    confidence: "High",
    trend: "Improving",
    lastUpdated: "2026-07-24T08:30:00.000Z",
  },
  summary: {
    relationship: {
      relationshipId: "REL-NW-2401",
      institutionId: "INS-NW-4401",
      relationshipName: "Northwind Maritime Primary Relationship",
      status: "active",
      stage: "growth",
      ownerDisplayName: "Ariane D.",
      createdDate: "2026-05-04",
      updatedDate: "2026-07-23",
      summaryMetadata: {
        sourceSystem: "relationship_workspace_projection",
        sourceReference: "REL-NW-2401",
        tags: ["customer-workspace", "relationship-journey"],
        attributeCount: 8,
      },
    },
    contactCount: "6",
    interactionCount: "18",
    primaryContactName: "Samir T.",
  },
  timeline: [
    {
      interactionId: "INT-REL-9001",
      relationshipId: "REL-NW-2401",
      interactionType: "review_meeting",
      subject: "Quarterly relationship review completed",
      occurredAt: "2026-07-23T10:15:00.000Z",
      participants: ["Ariane D.", "Samir T.", "Risk Lead"],
      status: "completed",
      summaryMetadata: {
        sourceSystem: "relationship_interactions",
        sourceReference: "INT-REL-9001",
        tags: ["quarterly", "governance"],
        attributeCount: 6,
      },
    },
    {
      interactionId: "INT-REL-9002",
      relationshipId: "REL-NW-2401",
      interactionType: "document_follow_up",
      subject: "Requested refreshed compliance certificate",
      occurredAt: "2026-07-22T14:40:00.000Z",
      participants: ["Operations", "Compliance Officer"],
      status: "in_progress",
      summaryMetadata: {
        sourceSystem: "relationship_interactions",
        sourceReference: "INT-REL-9002",
        tags: ["documents", "compliance"],
        attributeCount: 5,
      },
    },
    {
      interactionId: "INT-REL-9003",
      relationshipId: "REL-NW-2401",
      interactionType: "funding_preparation",
      subject: "Prepared funding readiness pre-brief",
      occurredAt: "2026-07-20T09:20:00.000Z",
      participants: ["Credit Analyst", "Relationship Manager"],
      status: "completed",
      summaryMetadata: {
        sourceSystem: "relationship_interactions",
        sourceReference: "INT-REL-9003",
        tags: ["funding", "brief"],
        attributeCount: 4,
      },
    },
  ],
  insights: [
    {
      id: "insight-rel-1",
      title: "Relationship momentum remains positive",
      summary: "Engagement cadence is stable with consistent owner and stakeholder participation.",
      category: "Engagement",
      confidence: "High",
    },
    {
      id: "insight-rel-2",
      title: "Document follow-up is the primary blocker",
      summary: "Outstanding compliance artifacts should be closed before escalating funding decisions.",
      category: "Readiness",
      confidence: "Medium",
    },
  ],
  nextActions: [
    {
      id: "action-rel-1",
      title: "Schedule funding readiness call",
      priority: "high",
      owner: "Relationship Manager",
      dueDate: "2026-07-26",
      status: "Open",
    },
    {
      id: "action-rel-2",
      title: "Collect refreshed compliance certificate",
      priority: "high",
      owner: "Operations",
      dueDate: "2026-07-27",
      status: "In Progress",
    },
    {
      id: "action-rel-3",
      title: "Prepare executive relationship brief",
      priority: "medium",
      owner: "Credit Analyst",
      dueDate: "2026-07-30",
      status: "Queued",
    },
  ],
};
